/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HomePageContent: typeof import('./components/panel/HomePageContent.vue')['default']
    LayerToggles: typeof import('./components/LayerToggles.vue')['default']
    MapPanelScreenShell: typeof import('./screens/MapPanelScreenShell.vue')['default']
    MapView: typeof import('./components/MapView.vue')['default']
    MobileViewportDock: typeof import('./components/MobileViewportDock.vue')['default']
    Panel: typeof import('./components/Panel.vue')['default']
    PanelContent: typeof import('./components/PanelContent.vue')['default']
    PanelPageSwitch: typeof import('./components/PanelPageSwitch.vue')['default']
    PanelToolbar: typeof import('./components/PanelToolbar.vue')['default']
    RoutePageContent: typeof import('./components/panel/RoutePageContent.vue')['default']
    RoutePicker: typeof import('./components/RoutePicker.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RoutesPageContent: typeof import('./components/panel/RoutesPageContent.vue')['default']
    StatusState: typeof import('./components/StatusState.vue')['default']
    StopDetail: typeof import('./components/route/StopDetail.vue')['default']
    StopFooter: typeof import('./components/route/StopFooter.vue')['default']
    StopHeader: typeof import('./components/route/StopHeader.vue')['default']
    StopPageContent: typeof import('./components/panel/StopPageContent.vue')['default']
    ThemeToggleButton: typeof import('./components/ThemeToggleButton.vue')['default']
    ToggleRow: typeof import('./components/ToggleRow.vue')['default']
    VehicleList: typeof import('./components/VehicleList.vue')['default']
  }
}
